### ISSUE TITLE
Regression: SPNEGO stopps working after update of spring-security 4.0.4.RELEASE to 4.2.1.RELEASE with big tokens

### ISSUE THREAD

**Issue by hohwille** [spring-projects/spring-security-kerberos#115]
We have successfully created an application based on spring-boot, spring-security-kerberos-web and many other spring artifacts with SPNEGO/Kerberos SSO based on active directory.

Now we had to upgrade some dependencies (new version of spring-boot, etc.) what also implied an update from version 4.0.4.RELEASE to version 4.2.1.RELEASE for these dependencies:
* spring-security-config
* spring-security-core
* spring-security-crypto
* spring-security-web

However, these are still in version 1.0.0.RELEASE (unchanged):
* spring-security-kerberos-core
* spring-security-kerberos-web

Since this upgrading change for only very few accounts the SSO now fails. From our current investigation these are accounts that have an extra-ordinary large number of groups/permissions associated and hence produce big kerberos tokens.
Also we have verified that when downgrading to our prior application version the error goes away so we can ensure that this is not an operational issue (network, AD infrastructure, etc.) but a software issue (bug in our application resp. the used third-party libraries).
We compared the diffs in git from the previous release to the current release and there are no changes at all related to our spring-security config. 
BTW: we are using spring-boot config as code (`WebSecurityConfigurerAdapter` with `KerberosAuthenticationProvider` and `KerberosServiceAuthenticationProvider`).

If the error occurs the user simply gets a white page in the browser what technically comes from an empty response with only these headers (in Browser debugger):
```
Transfer-Encoding: "chunked"
Date: ...
Connection: "close"
```
I also turned on debug flag in `GlobalSunJaasKerberosConfig` and set loglevels to debug. I get some helpful infos for successful logins but in the error case nothing is logged at all.

So:
* Do you have any clues?
* Do you have any ideas what we should try to trace down the bug?
* Do you need any further information?

I can not be 100% sure if the error is related to spring-security at all. If this will turn out as true, then sorry in advance for begging you at all. But even in that case it might be very helpful if others that face the same problem to find information about it.
The error might also be on a lower level. My other ideas is that a new version of spring boots embedded tomcat is silently rejecting the request when header is too large or whatever. However, we have these relevant settings for tomcat in our `application.properties`:
```
server.session.timeout=7200
server.session.cookie.max-age=36000
server.session.cookie.http-only=true
# max size of HTTP header has to be increased for Kerberos
server.tomcat.max-http-header-size=32768
```

**Comment by walterjs** [comment]
I don't have the code in front of me at the moment, so I can't be 100% sure of the version but the max header size property changed to be more generic in one of the later versions. Check this and make sure that 32k is big enough.

Hope this helps.

**Comment by hohwille** [comment]
indeed spring-boot changed propery names in an incompatible way on upgrade. See e.g. here:
https://github.com/spring-projects/spring-boot/issues/8066
```
server.tomcat.max-http-header-size=32768
```
is now simply ignored and has to be changed to
```
server.max-http-header-size=32768
```

Hope it might help others that have the same problem...
No Bug in spring-security-*.
