### ISSUE TITLE
Java 8 / Xdoclint

### ISSUE THREAD

**Issue by igler** [spring-projects/spring-security-kerberos#14]
If you are on Java 8 compiling fails because of an Xdoclint issue. If you modify the build.gradle file like this then compiling works again:
<pre><code>configure(allprojects) {
    ...
    [compileJava, compileTestJava]*.options*.compilerArgs = ['-Xlint:none']
	
    if (JavaVersion.current().isJava8Compatible()) {
        allprojects {
            tasks.withType(Javadoc) {
                options.addStringOption('Xdoclint:none', '-quiet')
            }
        }
    }

    test.systemProperty("java.awt.headless", "true")
    ...
</code></pre>

**Comment by jvalkeal** [comment]
Ah yeah this is just my mistake. Instead of tweaking build file, lemmy fix the errors.
