### ISSUE TITLE
local browser sends NTLM token instead of Kerberos token

### ISSUE THREAD

**Issue by kosmala** [spring-projects/spring-security-kerberos#149]
When calling my wildfly12-server secured with spring-security-kerberos from a local browser, I get a "GSSContext name of the context initiator is null". It works when calling from a collegue's workstation! looking at the logs it shows that the order of the preferred Mechanism Oids is different:
calling from local browser:
SpNegoToken NegTokenInit: reading Mechanism Oid = 1.3.6.1.4.1.311.2.2.10  
SpNegoToken NegTokenInit: reading Mechanism Oid = 1.2.840.48018.1.2.2  
SpNegoToken NegTokenInit: reading Mechanism Oid = 1.2.840.113554.1.2.2  
SpNegoToken NegTokenInit: reading Mechanism Oid = 1.3.6.1.4.1.311.2.2.30  
calling from remote browser:
SpNegoToken NegTokenInit: reading Mechanism Oid = 1.2.840.113554.1.2.2  
SpNegoToken NegTokenInit: reading Mechanism Oid = 1.2.840.48018.1.2.2  
SpNegoToken NegTokenInit: reading Mechanism Oid = 1.3.6.1.4.1.311.2.2.30
SpNegoToken NegTokenInit: reading Mechanism Oid = 1.3.6.1.4.1.311.2.2.10  
,i.e. the local browser sends NTLM as preferred mechanism whereas the remote browser sends Kerberos as preferred mechanism.

Having a look at the communication between server and remote browser with a sniffer, I see a response containg a header "WWW-Authenticate: Negotiate oRQwEqADCgEBoQsGCSqGSIb3EgECAg==" when communicating with a remote browser, which I don't see with the local browser.

Kerberos Authentication *works* with a local browser when using the same Kerberos-Konfiguration (i.e. keytab-file, SPN and krb5.ini are the same) and the org.jboss.security.negotiation.NegotiationAuthenticator as a valve (configured in jboss-web.xml) in JBoss EAP 6.4

Any idea why the JBoss org.jboss.security.negotiation.NegotiationAuthenticator makes the local browser send a correct kerberos token and spring-security-kerberos does not?

**Comment by jornfranke** [comment]
That means your Kerberos configuration is most likely wrong. You can check the following things:
The keytab of the technical user for Kerberos SSO does it contain the correct SPN? The SPN must be HTTP/example.org (use always capital letters). Check also the Kerberos encryption type that is set for the technical user in ActiveDirectory (if you use it, there are specific attributes to configure it, specifying it only when using ktpass/ktutil is not enough). Can your application access the keytab correctly? (Hint: Always perform an extra check in your application if the keytab is accessible and readable).

**Comment by kosmala** [comment]
First: thanks for your reply.
Second: if the Kerberos configuration was wrong, how come that it works with JBoss EAP 6.4? The configuration files are the same. Any idea?

**Comment by jornfranke** [comment]
I believe  you may not deliver all configuration information for Kerberos to spring-security-kerberos. Can you share some source code?

**Comment by kosmala** [comment]
unfortunately not, because I already left the company and have no access to the code any more :-/ sorry! So I think we have to simply close the issue.
