### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by chkpnt** [spring-projects/spring-security-kerberos#157]
Documentation is from 2015 and I can't import this project into IntelliJ due to the used and very old Gradle version.

**Comment by bedrin** [comment]
FYI - I'm maintaining an alternative implementation of Kerberos (with Spring support): https://github.com/bedrin/kerb4j

**Comment by rwinch** [comment]
Thanks for reaching out @chkpnt and thank you for your response @bedrin

We realize this project needs some attention and are looking into options to ensure it gets the attention it needs. In the near term, I'd consider taking a look at https://github.com/bedrin/kerb4j as it appears to have the support it needs.

**Comment by GyllingSW** [comment]
@rwinch - Any news on this? Do you still recommend using Kerb4J instead for new implementations?

**Comment by sergeykad** [comment]
The referenced https://github.com/bedrin/kerb4j project also looks dead. There was no single commit for over a year. The Kerberos integration future does not look good.

**Comment by bedrin** [comment]
> The referenced https://github.com/bedrin/kerb4j project also looks dead. There was no single commit for over a year. The Kerberos integration future does not look good.

It's not dead, but indeed there's no active development. I'm treating it as feature complete - hence no commits for over a year.
I'm open to improvement suggestions and/or contributions.

**Comment by CoderYellow** [comment]
I also maintained a version https://github.com/OpenProjectX/spring-security-kerberos

**Comment by jvalkeal** [comment]
Closing as we're preparing one RC and then a release.
