### ISSUE TITLE
Outdated documentation for Kerberos integration

### ISSUE THREAD

**Issue by sergeykad** [spring-projects/spring-security-kerberos#160]
**Describe the bug**
The documentation suggests using the deprecated `WebSecurityConfigurerAdapter` class for Kerberos integration.

**To Reproduce**
See the following links:
https://docs.spring.io/spring-security-kerberos/docs/current/reference/html/ssk-spnego.html
https://docs.spring.io/spring-security-kerberos/docs/current/reference/htmlsingle/

**Expected behavior**
There will be Kerberos integration examples aligned with the changes described here: https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter
As it is, there is no documentation about how Kerberos integration should work now.

**Comment by sjohnr** [comment]
Thanks for reaching out, @sergeykad!

See [this comment](https://github.com/spring-projects/spring-security-kerberos/issues/157#issuecomment-776736678). Unfortunately, I don't believe there's an update available at this time on spring-security-kerberos.

**Comment by sergeykad** [comment]
@sjohnr The project recommended in #157 also did not have commits for over a year and seems dead. Are there any additional options for Kerberos integration?

**Comment by sjohnr** [comment]
@sergeykad, I'm not personally aware of any, but I haven't spent much time with Kerberos integrations.

**Comment by jvalkeal** [comment]
Superseded by #176
