### ISSUE TITLE
Issue after Spring Boot upgrade to 3.0

### ISSUE THREAD

**Issue by marcin-doroz** [spring-projects/spring-security-kerberos#162]
Hi, 
I have received "java.lang.NoSuchMethodError: 'void org.springframework.http.client.HttpComponentsClientHttpRequestFactory.<init>(org.apache.http.client.HttpClient)'" in spring-security-kerberos-client (KerberosRestTemplate.class) after Spring Boot upgrade to 3.0. I believe HttpComponentsClientHttpRequestFactory expects org.apache.hc.client5.http.classic.HttpClient and receives 
org.apache.http.client.HttpClient.
![image](https://user-images.githubusercontent.com/97293939/210075031-7a2580d0-7e6e-417c-8cd7-eddab912fb99.png)
Are you going to adjust spring-security-kerberos-client to Spring Boot 3.* ?

**Comment by jvalkeal** [comment]
Closing as dup in favour or #165
