### ISSUE TITLE
spring-security-kerberos not compatable for jakarta 

### ISSUE THREAD

**Issue by venkatnaveen7** [spring-projects/spring-security-kerberos#163]
the last version 1.0.1 still uses  javax packages
import javax.servlet.FilterChain;
import javax.servlet.ServletException;
import javax.servlet.ServletRequest;
import javax.servlet.ServletResponse;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

this fails when we compile and run with the latest version of java 

any other ways to use spring-security-kerberos with latest version of java

**Comment by ivanfomkin** [comment]
> any other ways to use spring-security-kerberos with latest version of java

I think it's not possible
Maybe change imports to jakarta and compile can resolve problems, but this project is dead (a lot of time without updates) and in #157 you can see recommended alternative library

**Comment by jvalkeal** [comment]
Closing as dup in favour or #165
