### ISSUE TITLE
Can we expect a tentative release of 2.0.0

### ISSUE THREAD

**Issue by venkatnaveen7** [spring-projects/spring-security-kerberos#172]
DA Team
can we please expect a tentative release of 2.0.0

**Comment by hellokkiyer** [comment]
A tentative release date would help us to prepare better for our product. Thanks!

**Comment by jvalkeal** [comment]
We just released 2.0.0-M1. There's going to be one RC before a release. We don't have exact date yet but we're targeting within next two weeks.
