### ISSUE TITLE
NTLM token sent from client after enabling AES

### ISSUE THREAD

**Issue by venkatnaveen7** [spring-projects/spring-security-kerberos#173]
Team
we have disabled RC4_HMAC and allowed only AES algorithm types in the client machine
then when we try to hit the application URL we can only see NTLM token has been sent not the kerberos
however my AD supports AES too
any views on this please..?

**Comment by koraktor** [comment]
Is AES-128 / 256 enabled on the user accounts and the account of the SPN?

**Comment by venkatnaveen7** [comment]
I guess Yes
How do I verify it plz..?

**Comment by jvalkeal** [comment]
Can you tell more details about your setup. We're updating docs for a new release and it might be a good thing to mention in docs if I can reproduce it. Just to be sure, we're talking about spnego auth from a browser?

**Comment by venkatnaveen7** [comment]
Hi [jvalkeal](https://github.com/jvalkeal)   
we have generated keytab file using ktab utility of java17 and registered the SPN for servers
The issue was we don't see krb5 token in Wireshark tool network logs, we could see only the NTLM token  (here we used spring-security-kerberos-2.0.0.-SNAPSHOT)
later we did a force update of security policies from the AD side and disabled RC4 in the client's machine local security settings   (updated spring-security-kerberos-2.0.0-M1) and we could see the krb5 token in the network
