### ISSUE TITLE
Login issues with Spring Boot 3.3

### ISSUE THREAD

**Issue by eu-rlarsen** [spring-projects/spring-security-kerberos#195]
The artifact is working fine with latest Spring Boot 3.2.6 - but if we upgrade to Spring Boot 3.3.0, then it looks like the user / password is missing, and we get a 401.

Our code has been set up and used as in this sample: https://github.com/spring-projects/spring-security-kerberos/blob/main/spring-security-kerberos-samples/sec-client-rest-template/src/main/java/demo/app/Application.java

**Comment by eu-rlarsen** [comment]
The workaround from @Jeffrey-Hassan is working fine in our code too, after a small reorganization, because we were setting some timeouts on the HttpClient too, and this set up and the buildHttpClient() are now combined - and yeah an alternatives to Apache HttpClient need to be found.

**Comment by rwinch** [comment]
I've pushed an update to main which will be in the next release

**Comment by jwanglof** [comment]
Do you have an ETA when will the next release be published? :)
