### ISSUE TITLE
NPE in SunJaasKerberosTicketValidator with JDK 1.8.0_40

### ISSUE THREAD

**Issue by koraktor** [spring-projects/spring-security-kerberos#22]
While updating a project to 1.0.0.RC1 (from a customized 1.0.0.M2) I encountered the following error. The application ran fine with JDK 1.8.0, but updating to JDK 1.8.0_40 did completely break Kerberos authentication.

The error occurs inside [SunJaasKerberosTicketValidator.KerberosValidateAction#run](https://github.com/spring-projects/spring-security-kerberos/blob/1.0.0.RC1/spring-security-kerberos-core/src/main/java/org/springframework/security/extensions/kerberos/SunJaasKerberosTicketValidator.java#L160) because `context.getSrcName()` is `null`.

I have no idea why this doesn't work on JDK 1.8.0_40, yet.

 1. This should be fixed for JDK 1.8.0_40 (or any other affected versions). Maybe there is additional configuration needed.
 2. The implementation should be adapted to handle such cases more gracefully ([example](https://github.com/apache/cxf/blob/cxf-3.0.4/rt/frontend/jaxrs/src/main/java/org/apache/cxf/jaxrs/security/KerberosAuthenticationFilter.java#L95-L96)).

**Comment by jvalkeal** [comment]
Right, thanks reporting this. Feels like a bug to me in jdk but I agree, it's better to throw something else than npe.

**Comment by jvalkeal** [comment]
Related jdk bug may be this https://bugs.openjdk.java.net/browse/JDK-8078439.

**Comment by igler** [comment]
Had the same issues and downgrading to JDK 8u31 helped.
