### ISSUE TITLE
Move KerberosLdapContextSource to an ldap package

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security-kerberos#23]
This should be done to signal to users that the optional ldap dependency is necessary

**Comment by jvalkeal** [comment]
New jar package? Didn't we discuss that it's ok for ldap to be optional in a client package?

**Comment by rwinch** [comment]
@jvalkeal A new java package that would exist in the existing jar. If you look at optional dependencies in most of the spring jars they optional dependencies are contained within a subpackage within the jar. We should be doing this with the Kerberos project as well.

**Comment by jvalkeal** [comment]
@rwinch gotcha, sorry I misunderstood. Yeah it makes sense now :)

**Comment by rwinch** [comment]
@jvalkeal It's quite alright...I was pretty vague on the ticket. Sorry about that.
