### ISSUE TITLE
Version 1.0.0.RC2 not available from milestone repository

### ISSUE THREAD

**Issue by koraktor** [spring-projects/spring-security-kerberos#25]
[1.0.0.RC2](https://github.com/spring-projects/spring-security-kerberos/tree/1.0.0.RC2) has been tagged a few days ago, but is not yet available from http://repo.spring.io/milestone.

**Comment by jvalkeal** [comment]
@rwinch I think you made a simple mistake by promoting it into releases instead of milestones? 

http://repo.spring.io/release/org/springframework/security/kerberos/spring-security-kerberos-core/1.0.0.RC2/

**Comment by rwinch** [comment]
Thanks for the report @koraktor! @jvalkeal was correct that this was mistakenly put in the releases. The release should now be available in the milestone repository as expected.
