### ISSUE TITLE
FireFox falls back to form login

### ISSUE THREAD

**Issue by arashp** [spring-projects/spring-security-kerberos#26]
Hi Guys,

I just started using this framework. I built pom.xml using gradle and then created project for sec-server-spnego-form-auth project under sample. I then use IDE to compile and get all dependencies and the project built and run successfully. It works in IE and browser prompts shows and it uses the kerberos. But in Firefox it always falls back to login form. I already added the url into firefox negotiate.trusted-uris
I am opening browser from a different VM than the one has server code running. Please note below about my environment although I highly doubt if that causes issue:

1. The server where the code runs has FQDN of  mgkrb01.garr.local but I created an A alias in DNS server mgspringroot01.garr.local and points to same server. I then ran ktpass using the A alias (mgspringroot01.garr.local) and in .yml file specified the keytab and the account. I also run in port 9292 instead of 8080. and browse to http://mgspringroot01.garr.local:9292/home
when i click on home in IE it does show prompt but in firefox it takes me to login page.

I think it is a bug but please let me know If I am following everything right?

Thanks you very much for support

**Comment by jvalkeal** [comment]
Have you checked from boot/tomcat logs if firefox is sending spnego negotiate headers? If ie is working then it's easy to see how the logs should look like. I assume you run ie and firefox from a same host?

**Comment by koraktor** [comment]
Firefox has a pretty useful debug log for Kerberos authentication. You have to modify environment variables to enable it:

```shell
export NSPR_LOG_MODULES=negotiateauth:5
export NSPR_LOG_FILE=/tmp/moz.log
```

(Use `set` on Windows.)

Additionally, you might want to sniff the packets using Wireshark or similar.

**Comment by arashp** [comment]
Thanks Sebastian,

I think I found the issue but can not understand why. So in my server, I have 2 application that both uses kerberos. One is http://mgkrb01.garr.local/ and other is http://mgspringkrb01.garr.local:9292/ The latter is the one uses the spring kerberos extension the former is using SPnegoFilter from sourceforge API which is another way of implementing kerberos. But keep in mind they both point to same server in DNS. So the issue with FF is that I can not have both of these urls in the negotiate trust-uris . If I have only one of them they work but if I add them both one of them throw error. Do you know the reason behind this behaviour? Thanks

**Comment by jvalkeal** [comment]
Difficult to say, you should be able to separate uris with comma. Try different combinations like `http://` `.local`. It wouldn't surprise me if it's because other is missing port although it defaults to 80 then.

**Comment by jvalkeal** [comment]
Closing this now
