### ISSUE TITLE
Login with @domain

### ISSUE THREAD

**Issue by igler** [spring-projects/spring-security-kerberos#30]
If I take e.g. "user@COMPANY.DOM" or simply "user" as login and enter the correct password then it works. If I use "user@company.dom" then I get an error? Did I forgot to configure something? I assume the REALM-name is OK at the end but not the domain-name?

**Comment by jvalkeal** [comment]
which sample this is? kerberos realm's are, afaik, case sensitive.

**Comment by igler** [comment]
I adopted this sample (https://github.com/jvalkeal/spring-security-test-apps/tree/master/sec-server-spnego-form-auth/src) to my needs.

**Comment by jvalkeal** [comment]
Yeah, it is using that realm(COMPANY.DOM) to validate against krb server. 

Your krb5.conf probably have
```
[libdefaults]
	default_realm =COMPANY.DOM
```
where it gets a default. So I would not expect that to succeed with `company.dom`. Maybe we could add a flag which would i.e. uppercase realm name automatically.

Btw, samples are now in https://github.com/spring-projects/spring-security-kerberos/tree/master/spring-security-kerberos-samples and documented in ref docs.

**Comment by igler** [comment]
Yes, <code>[libdefaults]</code> in my file has this entry you wrote. That flag would be a good idea!

**Comment by jvalkeal** [comment]
Tracked in #31
