### ISSUE TITLE
SPNEGO auth fails if client proposes MS krb5 OID

### ISSUE THREAD

**Issue by jvalkeal** [spring-projects/spring-security-kerberos#34]
This issue relates to #22 and https://bugs.openjdk.java.net/browse/JDK-8078439. We should try to attempt if we can change framework code so that this bug is bypassed if jdk 1.8.0_40 or jdk 1.8.0_45 is used.

**Comment by jvalkeal** [comment]
paging @igler it'd be nice if you have time to test your stuff with 1.8.0_40 or jdk 1.8.0_45.

**Comment by igler** [comment]
You mean latest snapshot or release 1.0.1 with JDK 1.8.0_40 or ..._45?

**Comment by jvalkeal** [comment]
@igler we don't have 1.0.1.RELEASE yet, so either local build or http://repo.spring.io/libs-snapshot/org/springframework/security/kerberos/spring-security-kerberos-core/1.0.1.BUILD-SNAPSHOT/. 40/45 doesn't matter, I used 45 to test it.

**Comment by igler** [comment]
1.0.1.BUILD-SNAPSHOT works with JDK 1.8.0_45 now!

**Comment by jvalkeal** [comment]
@igler thx mate, wanted to get second pair of eyes.
