### ISSUE TITLE
Improve documentation of browser configuration for SPNEGO negotiation

### ISSUE THREAD

**Issue by saschaszott** [spring-projects/spring-security-kerberos#37]
Hi folks,

the documentation of the required browser configuration in order to activate SPNEGO negotation (Appendix E) should be improved. 

Here are some points that should be adapted:

Firefox
* the value for *network.negotiate-auth.delegation-uris* has to replaced with the server address if Kerberos delegation is required

Chrome
* on Windows machines (clients): Chrome shares the configuration with Internet Explorer so if all changes were applied to IE (as described in E.3), nothing has to be passed via command-line parameters
* on Linux/Mac OS machines (clients): the command-line parameter *--auth-negotiate-delegate-whitelist* should only used if Kerberos delegation is required (otherwise do not set this parameter)

Futhermore, a general note should be added that recommends to use https URIs for *auth-negotiate-delegate-whitelist* (Chrome) or *network.negotiate-auth.delegation-uris* (Firefox), respectively.

**Comment by jvalkeal** [comment]
ok, thanks looks good. I'll put these in.
