### ISSUE TITLE
Document Chrome Flags

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security-kerberos#6]
Chrome needs some extra flags to white list servers, they black list generally because they support NTLM and it’s pretty insecure. Once these were added it started working in Chrome:
 
"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --auth-server-whitelist="*.sample.local" --auth-negotiate-delegate-whitelist="*.sample.local"

**Comment by jvalkeal** [comment]
There's also some settings in firefox which needs to be tweaked beyond normal usage, `network.negotiate-auth.trusted-uris;https://`

**Comment by jvalkeal** [comment]
This stuff is in docs.
