### ISSUE TITLE
SES-71: Store delegating credential in the Authentication object

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security-kerberos#65]
[James Kirkwood](https://jira.spring.io/secure/ViewProfile.jspa?name=jkirkwood) (Migrated from [SES-71](https://jira.spring.io/browse/SES-71)) said:

We need to do delegated authentication with another kerberos based service.  Therefore we need the delegating credentials as provided by the GSSContext after accepting the client token.  Would it be possible to store the GSSCredential in the KerberosServiceRequestToken along with the principle?

It looks like the credentials need to be retrieved from the GSSContext in the KerberosValidateAction inner class of the SunJaasKerberosTicketValidator and returned along with the username (string) before the context is disposed.

I have a working version of this I'd be happy to attach (once I've added unit tests etc) if this is an appropriate enhancement.

**Comment by dariusan** [comment]
@bmustiata  Will there be a release of multi-tier support anytime soon?

**Comment by rwinch** [comment]
This was fixed in #91 No immediate plans for the milestone yet
