### ISSUE TITLE
Create a release artifact

### ISSUE THREAD

**Issue by phaas** [spring-projects/spring-security-kerberos#8]
The latest available maven artifact is from 2010:

http://maven.springframework.org/milestone/org/springframework/security/extensions/spring-security-kerberos-sample/

Please create and publish a release containing the current code. The only artifacts available currently are `-SNAPSHOT` jars, which are not suitable for use by downstream projects.

**Comment by jvalkeal** [comment]
Yes, this is going to happen pretty soon. I'm adding some client side functionality and then we go through one milestone and rc quickly to get release out.
