### ISSUE TITLE
SES-20: SpnegoAuthenticationProcessingFilter should extend AbstractAuthenticationProcessingFilter

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security-kerberos#80]
[Alejandro Alanis](https://jira.spring.io/secure/ViewProfile.jspa?name=alanis) (Migrated from [SES-20](https://jira.spring.io/browse/SES-20)) said:

since the SpnegoAuthenticationProcessingFilter does not extend the AbstractAuthenticationProcessingFilter, basic workflow events like AuthenticationSuccess- or AuthenticationFailerHandlers are not configurable. Shouldn't this be the case?

It would be easy then to define some handlers according to authentication success or failure without having to implement everything manually.

**Comment by spring-issuemaster** [comment]
This issue is related to #77
