### ISSUE TITLE
SpnegoAuthenticationProcessingFilter should not continue filter chain on successful authentication

### ISSUE THREAD

**Issue by alt250** [spring-projects/spring-security-kerberos#96]
Currently SpnegoAuthenticationProcessingFilter.doFilter() is doing

```
        if (header != null && (header.startsWith("Negotiate ") || header.startsWith("Kerberos "))) {
...
            if (successHandler != null) {
                successHandler.onAuthenticationSuccess(request, response, authentication);
            }
        }
        chain.doFilter(request, response);
```

when successHandler is SimpleUrlAuthenticationSuccessHandler, the success handler will commit  the response thus continuing the filter chain will fail with "IllegalStateException Committed" if a downstream filter calls response.send*()

**Comment by rwinch** [comment]
Marking as duplicate in favor of the pull request gh-97
